import type {
  Activity,
  Aggregator,
  MiniConnector,
  Execution,
  ExecutionLog,
  Workflow,
  PaletteNode,
} from "./types"

// ─── Dashboard Stats ──────────────────────────────────
export const dashboardStats = {
  activeWorkflows: 12,
  successRate: 98.7,
  failedLast24h: 3,
  totalExecutions: 1247,
  recordsProcessed: 2_340_000,
  avgDuration: 4200, // ms
}

// ─── Recent Activity ──────────────────────────────────
export const recentActivities: Activity[] = [
  {
    id: "act-001",
    workflowName: "SAP Orders → Salesforce",
    status: "success",
    startedAt: new Date(Date.now() - 300_000),
    duration: 3200,
    recordsProcessed: 156,
    source: "SAP B1",
    destination: "Salesforce",
  },
  {
    id: "act-002",
    workflowName: "Tally Invoices → Snowflake",
    status: "success",
    startedAt: new Date(Date.now() - 900_000),
    duration: 5400,
    recordsProcessed: 892,
    source: "Tally Prime",
    destination: "Snowflake",
  },
  {
    id: "act-003",
    workflowName: "Oracle HR → HubSpot",
    status: "failed",
    startedAt: new Date(Date.now() - 1_800_000),
    duration: 1200,
    recordsProcessed: 0,
    source: "Oracle DB",
    destination: "HubSpot",
  },
  {
    id: "act-004",
    workflowName: "SAP Inventory Sync",
    status: "running",
    startedAt: new Date(Date.now() - 60_000),
    duration: 0,
    recordsProcessed: 45,
    source: "SAP HANA",
    destination: "Snowflake",
  },
  {
    id: "act-005",
    workflowName: "Tally Ledger → BigQuery",
    status: "success",
    startedAt: new Date(Date.now() - 3_600_000),
    duration: 8900,
    recordsProcessed: 2340,
    source: "Tally Prime",
    destination: "BigQuery",
  },
  {
    id: "act-006",
    workflowName: "CRM Contact Sync",
    status: "pending",
    startedAt: new Date(Date.now() - 7_200_000),
    duration: 0,
    recordsProcessed: 0,
    source: "Salesforce",
    destination: "SAP B1",
  },
]

// ─── Mini Connectors ──────────────────────────────────
export const miniConnectors: MiniConnector[] = [
  {
    id: "mc-001",
    name: "Mumbai Office - Primary",
    status: "online",
    ipAddress: "192.168.1.100",
    version: "1.2.4",
    lastSeen: new Date(Date.now() - 30_000),
    os: "linux",
    cpuUsage: 23,
    memoryUsage: 45,
    activeWorkflows: 5,
  },
  {
    id: "mc-002",
    name: "Delhi Warehouse",
    status: "online",
    ipAddress: "10.0.0.55",
    version: "1.2.4",
    lastSeen: new Date(Date.now() - 60_000),
    os: "windows",
    cpuUsage: 12,
    memoryUsage: 38,
    activeWorkflows: 3,
  },
  {
    id: "mc-003",
    name: "Bangalore Dev Server",
    status: "warning",
    ipAddress: "172.16.0.10",
    version: "1.1.9",
    lastSeen: new Date(Date.now() - 300_000),
    os: "linux",
    cpuUsage: 78,
    memoryUsage: 82,
    activeWorkflows: 8,
  },
  {
    id: "mc-004",
    name: "Chennai Backup",
    status: "offline",
    ipAddress: "192.168.2.200",
    version: "1.2.3",
    lastSeen: new Date(Date.now() - 86_400_000),
    os: "linux",
    cpuUsage: 0,
    memoryUsage: 0,
    activeWorkflows: 0,
  },
]

// ─── Aggregators (Marketplace) ────────────────────────
export const aggregators: Aggregator[] = [
  {
    id: "agg-001",
    name: "SAP Business One",
    description: "Full bidirectional sync with SAP B1 modules including orders, inventory, and financials.",
    category: "ERP",
    logoUrl: "/logos/sap.svg",
    version: "2.1.0",
    installs: 1240,
    rating: 4.8,
    isInstalled: true,
    author: "360Solve",
    tags: ["erp", "sap", "orders", "inventory"],
  },
  {
    id: "agg-002",
    name: "Tally Prime",
    description: "Connect Tally Prime accounting data including ledgers, vouchers, and stock items.",
    category: "ERP",
    logoUrl: "/logos/tally.svg",
    version: "1.8.2",
    installs: 890,
    rating: 4.6,
    isInstalled: true,
    author: "360Solve",
    tags: ["erp", "tally", "accounting", "ledger"],
  },
  {
    id: "agg-003",
    name: "Salesforce",
    description: "Sync contacts, opportunities, leads, and custom objects with Salesforce CRM.",
    category: "CRM",
    logoUrl: "/logos/salesforce.svg",
    version: "3.0.1",
    installs: 3200,
    rating: 4.9,
    isInstalled: false,
    author: "360Solve",
    tags: ["crm", "salesforce", "contacts", "leads"],
  },
  {
    id: "agg-004",
    name: "Snowflake",
    description: "Load and sync data with Snowflake data warehouse. Supports bulk and incremental loads.",
    category: "Database",
    logoUrl: "/logos/snowflake.svg",
    version: "2.4.0",
    installs: 2100,
    rating: 4.7,
    isInstalled: true,
    author: "360Solve",
    tags: ["database", "warehouse", "analytics", "snowflake"],
  },
  {
    id: "agg-005",
    name: "HubSpot",
    description: "Two-way sync for contacts, companies, deals, and marketing data with HubSpot.",
    category: "CRM",
    logoUrl: "/logos/hubspot.svg",
    version: "1.5.0",
    installs: 1560,
    rating: 4.5,
    isInstalled: false,
    author: "360Solve",
    tags: ["crm", "hubspot", "marketing", "contacts"],
  },
  {
    id: "agg-006",
    name: "Oracle Database",
    description: "Direct connection to Oracle DB with support for stored procedures and complex queries.",
    category: "Database",
    logoUrl: "/logos/oracle.svg",
    version: "2.0.3",
    installs: 780,
    rating: 4.4,
    isInstalled: false,
    author: "360Solve",
    tags: ["database", "oracle", "sql", "enterprise"],
  },
  {
    id: "agg-007",
    name: "Google BigQuery",
    description: "Stream or batch load data into BigQuery for analytics and reporting.",
    category: "Analytics",
    logoUrl: "/logos/bigquery.svg",
    version: "1.9.1",
    installs: 1890,
    rating: 4.7,
    isInstalled: false,
    author: "360Solve",
    tags: ["analytics", "bigquery", "google", "warehouse"],
  },
  {
    id: "agg-008",
    name: "PostgreSQL",
    description: "Connect to any PostgreSQL database for reads and writes with full schema support.",
    category: "Database",
    logoUrl: "/logos/postgres.svg",
    version: "2.2.1",
    installs: 2450,
    rating: 4.8,
    isInstalled: true,
    author: "360Solve",
    tags: ["database", "postgres", "sql", "open-source"],
  },
  {
    id: "agg-009",
    name: "Microsoft Dynamics",
    description: "Integrate with Dynamics 365 for finance, operations, and customer engagement.",
    category: "ERP",
    logoUrl: "/logos/dynamics.svg",
    version: "1.3.0",
    installs: 620,
    rating: 4.3,
    isInstalled: false,
    author: "360Solve",
    tags: ["erp", "microsoft", "dynamics", "finance"],
  },
  {
    id: "agg-010",
    name: "Slack",
    description: "Send notifications, alerts, and reports to Slack channels and users.",
    category: "Communication",
    logoUrl: "/logos/slack.svg",
    version: "1.1.0",
    installs: 3400,
    rating: 4.6,
    isInstalled: true,
    author: "360Solve",
    tags: ["communication", "slack", "notifications", "alerts"],
  },
  {
    id: "agg-011",
    name: "AWS S3",
    description: "Read and write files to Amazon S3 buckets with support for CSV, JSON, and Parquet.",
    category: "Cloud",
    logoUrl: "/logos/aws.svg",
    version: "2.0.0",
    installs: 2890,
    rating: 4.8,
    isInstalled: false,
    author: "360Solve",
    tags: ["cloud", "aws", "s3", "storage"],
  },
  {
    id: "agg-012",
    name: "Zoho CRM",
    description: "Sync leads, contacts, accounts, and deals with Zoho CRM.",
    category: "CRM",
    logoUrl: "/logos/zoho.svg",
    version: "1.4.2",
    installs: 540,
    rating: 4.2,
    isInstalled: false,
    author: "360Solve",
    tags: ["crm", "zoho", "leads", "contacts"],
  },
]

// ─── Workflows ────────────────────────────────────────
export const workflows: Workflow[] = [
  {
    id: "wf-001",
    name: "SAP Orders → Salesforce",
    description: "Sync new SAP orders to Salesforce opportunities every 15 minutes",
    status: "active",
    lastRun: new Date(Date.now() - 300_000),
    nextRun: new Date(Date.now() + 600_000),
    successRate: 99.2,
    totalRuns: 1456,
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-02-01"),
  },
  {
    id: "wf-002",
    name: "Tally Invoices → Snowflake",
    description: "Daily batch load of Tally invoice data to Snowflake",
    status: "active",
    lastRun: new Date(Date.now() - 900_000),
    nextRun: new Date(Date.now() + 43_200_000),
    successRate: 97.8,
    totalRuns: 365,
    createdAt: new Date("2025-01-20"),
    updatedAt: new Date("2025-01-28"),
  },
  {
    id: "wf-003",
    name: "Oracle HR → HubSpot",
    description: "Sync employee records from Oracle to HubSpot contacts",
    status: "inactive",
    lastRun: new Date(Date.now() - 1_800_000),
    nextRun: null,
    successRate: 85.3,
    totalRuns: 230,
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date("2025-02-05"),
  },
  {
    id: "wf-004",
    name: "SAP Inventory Sync",
    description: "Real-time inventory level sync between SAP HANA and Snowflake",
    status: "active",
    lastRun: new Date(Date.now() - 60_000),
    nextRun: new Date(Date.now() + 300_000),
    successRate: 99.9,
    totalRuns: 8900,
    createdAt: new Date("2024-11-01"),
    updatedAt: new Date("2025-01-15"),
  },
  {
    id: "wf-005",
    name: "CRM Contact Sync",
    description: "Bidirectional contact sync between Salesforce and SAP B1",
    status: "draft",
    lastRun: null,
    nextRun: null,
    successRate: 0,
    totalRuns: 0,
    createdAt: new Date("2025-02-04"),
    updatedAt: new Date("2025-02-04"),
  },
]

// ─── Executions ───────────────────────────────────────
function generateLogs(status: string): ExecutionLog[] {
  const base: ExecutionLog[] = [
    {
      id: "log-1",
      timestamp: new Date(Date.now() - 10_000),
      level: "info",
      message: "Workflow execution started",
    },
    {
      id: "log-2",
      timestamp: new Date(Date.now() - 8_000),
      level: "info",
      message: "Connected to source database",
    },
    {
      id: "log-3",
      timestamp: new Date(Date.now() - 6_000),
      level: "info",
      message: "Extracting records from source...",
    },
  ]

  if (status === "failed") {
    base.push({
      id: "log-4",
      timestamp: new Date(Date.now() - 4_000),
      level: "error",
      message: "Connection refused by destination. Error: ECONNREFUSED 10.0.0.55:5432",
      metadata: { errorCode: "CONN_REFUSED", retryCount: 3 },
    })
  } else {
    base.push(
      {
        id: "log-4",
        timestamp: new Date(Date.now() - 4_000),
        level: "info",
        message: "Transform: Applied 3 mapping rules",
      },
      {
        id: "log-5",
        timestamp: new Date(Date.now() - 2_000),
        level: "info",
        message: "Loading records to destination...",
      },
      {
        id: "log-6",
        timestamp: new Date(Date.now() - 500),
        level: "info",
        message: "Execution completed successfully",
      }
    )
  }

  return base
}

export const executions: Execution[] = [
  {
    id: "exec-001",
    workflowId: "wf-001",
    workflowName: "SAP Orders → Salesforce",
    status: "success",
    startedAt: new Date(Date.now() - 300_000),
    completedAt: new Date(Date.now() - 296_800),
    duration: 3200,
    recordsProcessed: 156,
    recordsFailed: 0,
    triggeredBy: "schedule",
    logs: generateLogs("success"),
  },
  {
    id: "exec-002",
    workflowId: "wf-002",
    workflowName: "Tally Invoices → Snowflake",
    status: "success",
    startedAt: new Date(Date.now() - 900_000),
    completedAt: new Date(Date.now() - 894_600),
    duration: 5400,
    recordsProcessed: 892,
    recordsFailed: 2,
    triggeredBy: "schedule",
    logs: generateLogs("success"),
  },
  {
    id: "exec-003",
    workflowId: "wf-003",
    workflowName: "Oracle HR → HubSpot",
    status: "failed",
    startedAt: new Date(Date.now() - 1_800_000),
    completedAt: new Date(Date.now() - 1_798_800),
    duration: 1200,
    recordsProcessed: 0,
    recordsFailed: 0,
    triggeredBy: "manual",
    logs: generateLogs("failed"),
  },
  {
    id: "exec-004",
    workflowId: "wf-004",
    workflowName: "SAP Inventory Sync",
    status: "running",
    startedAt: new Date(Date.now() - 60_000),
    completedAt: null,
    duration: 0,
    recordsProcessed: 45,
    recordsFailed: 0,
    triggeredBy: "schedule",
    logs: generateLogs("running"),
  },
  {
    id: "exec-005",
    workflowId: "wf-001",
    workflowName: "SAP Orders → Salesforce",
    status: "success",
    startedAt: new Date(Date.now() - 3_600_000),
    completedAt: new Date(Date.now() - 3_596_500),
    duration: 3500,
    recordsProcessed: 203,
    recordsFailed: 1,
    triggeredBy: "schedule",
    logs: generateLogs("success"),
  },
  {
    id: "exec-006",
    workflowId: "wf-002",
    workflowName: "Tally Invoices → Snowflake",
    status: "success",
    startedAt: new Date(Date.now() - 7_200_000),
    completedAt: new Date(Date.now() - 7_194_200),
    duration: 5800,
    recordsProcessed: 1024,
    recordsFailed: 0,
    triggeredBy: "webhook",
    logs: generateLogs("success"),
  },
  {
    id: "exec-007",
    workflowId: "wf-003",
    workflowName: "Oracle HR → HubSpot",
    status: "failed",
    startedAt: new Date(Date.now() - 10_800_000),
    completedAt: new Date(Date.now() - 10_798_500),
    duration: 1500,
    recordsProcessed: 34,
    recordsFailed: 34,
    triggeredBy: "schedule",
    logs: generateLogs("failed"),
  },
  {
    id: "exec-008",
    workflowId: "wf-004",
    workflowName: "SAP Inventory Sync",
    status: "success",
    startedAt: new Date(Date.now() - 14_400_000),
    completedAt: new Date(Date.now() - 14_397_800),
    duration: 2200,
    recordsProcessed: 567,
    recordsFailed: 0,
    triggeredBy: "schedule",
    logs: generateLogs("success"),
  },
]

// ─── Workflow Palette Nodes (Source → Transform → Destination) ─────
export const paletteNodes = {
  source: [
    { id: "node-db-source", type: "source" as const, label: "Database", description: "Connect with credentials or connection string", icon: "Database", connectionMethod: "credentials" as const },
    { id: "node-api-source", type: "source" as const, label: "Custom API", description: "Pull data from your own REST API", icon: "Globe", connectionMethod: "custom_api" as const },
    { id: "node-agg-source", type: "source" as const, label: "Aggregator", description: "Use a pre-built marketplace connector", icon: "Store", connectionMethod: "aggregator" as const },
    { id: "node-connstr-source", type: "source" as const, label: "Connection String", description: "Direct connection string to any database", icon: "Link", connectionMethod: "connection_string" as const },
    { id: "node-csv-source", type: "source" as const, label: "File / CSV", description: "Upload or stream from files", icon: "FileSpreadsheet", connectionMethod: "custom_api" as const },
  ],
  transform: [
    { id: "node-ai-transform", type: "transform" as const, label: "AI Transform", description: "AI-assisted data mapping & conversion", icon: "Sparkles" },
    { id: "node-map", type: "transform" as const, label: "Field Mapper", description: "Map fields between schemas", icon: "ArrowLeftRight" },
    { id: "node-filter", type: "transform" as const, label: "Filter", description: "Filter records by condition", icon: "Filter" },
    { id: "node-aggregate", type: "transform" as const, label: "Aggregate", description: "Group and aggregate data", icon: "Layers" },
    { id: "node-script", type: "transform" as const, label: "Custom Script", description: "Run custom TypeScript logic", icon: "Code" },
  ],
  destination: [
    { id: "node-db-dest", type: "destination" as const, label: "Database", description: "Write to any database with credentials", icon: "Database", connectionMethod: "credentials" as const },
    { id: "node-api-dest", type: "destination" as const, label: "Custom API", description: "Push data to your own REST API", icon: "Globe", connectionMethod: "custom_api" as const },
    { id: "node-agg-dest", type: "destination" as const, label: "Aggregator", description: "Use a pre-built marketplace connector", icon: "Store", connectionMethod: "aggregator" as const },
    { id: "node-connstr-dest", type: "destination" as const, label: "Connection String", description: "Direct connection string to any database", icon: "Link", connectionMethod: "connection_string" as const },
    { id: "node-webhook-dest", type: "destination" as const, label: "Webhook", description: "POST data to a webhook URL", icon: "Webhook", connectionMethod: "custom_api" as const },
  ],
}

// ─── AI Assistant preset messages ────────────────────
export const aiPresetMessages = [
  "Transfer all orders from my PostgreSQL to Snowflake",
  "Set up a sync from SAP Business One to Salesforce",
  "Create a pipeline from my REST API to BigQuery",
  "Help me map fields from Oracle DB to a webhook",
]
